In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from os import listdir
from tensorflow.keras.preprocessing import sequence
import tensorflow as tfs
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.layers import LSTM

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten, Conv2D, MaxPooling2D,LeakyReLU,MaxPool2D
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2, random

In [2]:
height=32
width=32
depth=3

inputShape = (height, width, depth)

In [3]:
# Prepare the train and test dataset.
from tensorflow import keras
# batch_size = 64
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
print(x_train.shape)
# Normalize data
x_train = x_train.astype("float32") / 255.0
x_train = np.reshape(x_train, (-1, 32, 32, 3))

x_test = x_test.astype("float32") / 255.0
x_test = np.reshape(x_test, (-1, 32, 32, 3))
y_train=np.reshape(y_train,(-1))
y_test=np.reshape(y_test,(-1))

170508288/170498071 [==============================] - 2s 0us/step
(50000, 32, 32, 3)


In [4]:
from  keras.utils import np_utils
# y_train = np_utils.to_categorical(y_train)
# y_test= np_utils.to_categorical(y_test)
print(y_train[0])
print(y_train.shape,y_test.shape)
print(x_train.shape)
print(y_train[0],x_train[0])

6
(50000,) (10000,)
(50000, 32, 32, 3)
6 [[[0.23137255 0.24313726 0.24705882]
  [0.16862746 0.18039216 0.1764706 ]
  [0.19607843 0.1882353  0.16862746]
  ...
  [0.61960787 0.5176471  0.42352942]
  [0.59607846 0.49019608 0.4       ]
  [0.5803922  0.4862745  0.40392157]]

 [[0.0627451  0.07843138 0.07843138]
  [0.         0.         0.        ]
  [0.07058824 0.03137255 0.        ]
  ...
  [0.48235294 0.34509805 0.21568628]
  [0.46666667 0.3254902  0.19607843]
  [0.47843137 0.34117648 0.22352941]]

 [[0.09803922 0.09411765 0.08235294]
  [0.0627451  0.02745098 0.        ]
  [0.19215687 0.10588235 0.03137255]
  ...
  [0.4627451  0.32941177 0.19607843]
  [0.47058824 0.32941177 0.19607843]
  [0.42745098 0.28627452 0.16470589]]

 ...

 [[0.8156863  0.6666667  0.3764706 ]
  [0.7882353  0.6        0.13333334]
  [0.7764706  0.6313726  0.10196079]
  ...
  [0.627451   0.52156866 0.27450982]
  [0.21960784 0.12156863 0.02745098]
  [0.20784314 0.13333334 0.07843138]]

 [[0.7058824  0.54509807 0.376470

In [5]:
from sklearn.utils import shuffle
x_train, y_train= shuffle(x_train, y_train, random_state=42)
X=[]
Y=[]
j=0
for i in range(20):
  X.append(x_train[j:j+2500])
  Y.append(y_train[j:j+2500])
  j+=2500



In [6]:
X=np.array(X)
Y=np.array(Y)
print(X.shape,Y.shape)

(20, 2500, 32, 32, 3) (20, 2500)


In [7]:
from tensorflow.keras.layers import BatchNormalization
class MODEL:
    @staticmethod
    def build(nl):
        # model = Sequential()
        # model.add(Conv2D(32/nl,(3,3),strides=(2, 2), padding="same",input_shape=[32,32,3]) )
        # model.add(Conv2D(32/nl,(3,3),strides=(2, 2), padding="same") )
        # model.add(MaxPooling2D(pool_size=(2, 2),strides=2))
        # model.add(Conv2D(64/nl,(3,3),strides=(2, 2), padding="same") )
        # model.add(Conv2D(64/nl,(3,3),strides=(2, 2), padding="same") )
        # model.add(MaxPooling2D(pool_size=(2, 2),strides=2))

        # # model.add(Conv2D(512/nl,(3,3),strides=(2, 2), padding="same") )
        # # model.add(LeakyReLU(alpha=0.2))
        # # model.add(MaxPooling2D(pool_size=(2, 2)))
        # # model.add(Dropout(0.25))

        # # model.add(Conv2D(512/nl, (3, 3), strides=(2, 2), padding="same") )
        # model.add(Dropout(0.5))
        # model.add(Flatten())
        # model.add(Dense(128/nl,activation='relu'))
        # model.add(Dense(10,activation='softmax'))#for output layer

        # model = Sequential()
        # model.add(Conv2D(64/nl, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(32, 32, 3)))
        # model.add(Conv2D(64/nl, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        # model.add(MaxPooling2D((2, 2)))
        # model.add(Conv2D(128/nl, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        # model.add(Conv2D(128/nl, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        # model.add(MaxPooling2D((2, 2)))
        # model.add(Flatten())
        # model.add(Dense(256/nl, activation='relu', kernel_initializer='he_uniform'))
        # model.add(Dense(10))
        model = Sequential()
        model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(32, 32, 3)))
        model.add(BatchNormalization())
        model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPool2D((2, 2)))
        model.add(Dropout(0.2))
        model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPool2D((2, 2)))
        model.add(Dropout(0.3))
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPool2D((2, 2)))
        model.add(Dropout(0.4))
        model.add(Flatten())
        model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
        model.add(BatchNormalization())
        model.add(Dropout(0.5))
        model.add(Dense(10))

        return model

In [8]:
from sklearn.metrics import accuracy_score
def test_model(X_test, Y_test,  model, comm_round):
    # cce = tf.keras.losses.SparseCategoricalCrossentropy()
    # #logits = model.predict(X_test, batch_size=100)
    # logits = model.predict(X_test)
    # loss = cce(Y_test, logits)
    # acc = accuracy_score(tf.argmax(logits, axis=1), tf.argmax(Y_test, axis=1))
    # print('comm_round: {} | global_acc: {:.3%} | global_loss: {}'.format(comm_round, acc, loss))
    model.compile(  optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)
    # loss,acc=model.evaluate(x_test,y_test)
    acc,loss=model.evaluate(x_test,y_test)
    return acc, loss
def scale_model_weights(weight, scalar):
    '''function for scaling a models weights'''
    weight_final = []
    steps = len(weight)
    for i in range(steps):
        weight_final.append(scalar * weight[i])
    return weight_final

def sum_scaled_weights(scaled_weight_list):
    '''Return the sum of the listed scaled weights. The is equivalent to scaled avg of the weights'''
    avg_grad = list()
    #get the average grad accross all client gradients
    for grad_list_tuple in zip(*scaled_weight_list):
        layer_mean = tf.math.reduce_sum(grad_list_tuple, axis=0)
        avg_grad.append(layer_mean)
      
    return avg_grad

In [9]:
from tensorflow import keras
from tensorflow.keras.models import clone_model

In [ ]:
global1= MODEL()
global_model = global1.build(1)
comms_round = 50
# print(trainy[2].shape)
from tensorflow.keras import backend as K
f= open("MyFileHeteroCifar10.txt", "a+") 
f.close()
for comm_round in range(40):
  f= open("MyFileHeteroCifar10.txt", "a+") 
  print("Comm_Round:",comm_round)

  global_weights = global_model.get_weights()
  scaled_local_weight_list = list()

  clientcluster=[[0,1,2,3,4],[5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19]]
  downsize=8
  inpchannel=-1
  opchannel=-1
  index=0
  for clstr in reversed(clientcluster):
    downsize=downsize/2
    cluster=MODEL()
    cluster_model=cluster.build(downsize)
    print("CLuster NO.",index)
    f.write("CLuster NO. %d \n" %index)
    index=index+1

    nmlayers=len(cluster_model.layers)
    for i in range(0,nmlayers):
      if(len(cluster_model.layers[i].get_weights())==2):
        print(i)
        wt,bs=cluster_model.layers[i].get_weights()
        wt1,bs1=global_model.layers[i].get_weights()
        
        # print(wt.shape[2],bs.shape[0])
        # print(wt2.shape,bs2.shape)
        # print(wt.shape)
        if(i==0):
          wt=wt1[:wt.shape[0],:wt.shape[1],:wt.shape[2],:wt.shape[3]]
          # bs=bs1[:bs.shape[0]]
        elif(i==nmlayers-4):
          wt=wt1[:wt.shape[0],:wt.shape[1]]
          # bs=bs1[:bs.shape[0]]

        elif(i==nmlayers-1):
          wt=wt1[:wt.shape[0],:wt.shape[1]]
          # bs=bs1[:bs.shape[0]]
        else:
          wt=wt1[:wt.shape[0],:wt.shape[1],:wt.shape[2],:wt.shape[3]]
          # bs=bs1[:bs.shape[0]]
        
        cluster_model.layers[i].set_weights([wt,bs])
      if(len(cluster_model.layers[i].get_weights())==4):
        a,b,c,d=cluster_model.layers[i].get_weights()
        a1,b1,c1,d1=global_model.layers[i].get_weights()
        print(a.shape[0])
        a=a1[:a.shape[0]]
        b=b1[:b.shape[0]]
        c=c1[:c.shape[0]]
        d=d1[:d.shape[0]]
        cluster_model.layers[i].set_weights([a,b,c,d])











    for globalrounds in range(1):
      print("Cluster Rounds:",globalrounds)
      cluster_weights=cluster_model.get_weights()
      scaled_local_weight_list = list()
      for clients in clstr:
        print("Client No:",clients)
        local = MODEL()
        local_model=local.build(downsize)
        local_model.compile(optimizer=keras.optimizers.Adam(),
        loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=[keras.metrics.SparseCategoricalAccuracy()],
    )
        
        local_model.set_weights(cluster_weights)
        #trainy[ind]=np.array(trainy[ind]).reshape(-1,1)
        history=local_model.fit(X[clients],Y[clients], epochs=10)#,validation_data=(x_test,y_test))
        # print("Accuracy: ",history.history["accuracy"][4])
        # local_model.evaluate(x_test, y_test)
        local_loss, local_acc = test_model(x_test,y_test, local_model, comm_round)
        f.write("Communication Round: %d Client No: %d Local Model ACCURACY: %f LOSS: %f \n" %(comm_round ,clients,local_acc ,local_loss))
        scaling_factor=1.0/len(clstr) #1/no.ofclients
        scaled_weights = scale_model_weights(local_model.get_weights(), scaling_factor)
        scaled_local_weight_list.append(scaled_weights)
        K.clear_session()
      average_weights = sum_scaled_weights(scaled_local_weight_list)
      #global_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])

      nmlayers=len(cluster_model.layers)
      tmp_model=MODEL.build(downsize)
      tmp_model.set_weights(cluster_model.get_weights())
      # print(cluster_model.layers[4].get_weights())


      cluster_model.set_weights(average_weights)
      # print(cluster_model.layers[4].get_weights())
      if(clstr==clientcluster[-1]):
        for i in range(1,nmlayers-1):
          if(len(cluster_model.layers[i].get_weights())==2):
            wt,bs=global_model.layers[i].get_weights()
            wt1,bs1=cluster_model.layers[i].get_weights()
            # wt2,bs2=prev_model.layers[i].get_weights()
            print(i)
            # print(wt.shape[2],bs.shape[0])
            # print(wt2.shape,bs2.shape)
            print(wt.shape)
            # wt[:,:,:wt2.shape[2],:wt2.shape[3]]=wt2[:,:,:wt2.shape[2],:wt2.shape[3]]
            
            if(i==nmlayers-4):
              wt[:wt1.shape[0],:wt1.shape[1]]=wt1
              # bs[:bs1.shape[0]]=bs1

            else:
              wt[:wt1.shape[0],:wt1.shape[1],:wt1.shape[2],:wt1.shape[3]]=wt1
              # bs[:bs1.shape[0]]=bs1
            global_model.layers[i].set_weights([wt,bs])
          if(len(cluster_model.layers[i].get_weights())==4):
            a,b,c,d=cluster_model.layers[i].get_weights()
            a1,b1,c1,d1=global_model.layers[i].get_weights()
            a1[:a.shape[0]]=a
            b1[:b.shape[0]]=b
            c1[:c.shape[0]]=c
            d1[:d.shape[0]]=d
            global_model.layers[i].set_weights([a1,b1,c1,d1])



      elif(clstr!=clientcluster[-1]):
        for i in range(1,nmlayers-1):
          if(len(cluster_model.layers[i].get_weights())==2):
            wt,bs=global_model.layers[i].get_weights()
            wt1,bs1=cluster_model.layers[i].get_weights()
            wt2,bs2=prev_model.layers[i].get_weights()
            print(i)
            # print(wt.shape[2],bs.shape[0])
            print(wt2.shape,bs2.shape)
            print(wt1.shape)
            # wt[:,:,:wt2.shape[2],:wt2.shape[3]]=wt2[:,:,:wt2.shape[2],:wt2.shape[3]]
            
            # if(i==0):
            #   wt[:,:,:,wt2.shape[3]:wt1.shape[3]]=wt1[:,:,:,wt2.shape[3]:wt1.shape[3]]
            #   # bs[bs2.shape[0]:bs1.shape[0]]=bs1[bs2.shape[0]:bs1.shape[0]]
            # el
            if(i==nmlayers-4):
              wt[wt2.shape[0]:wt1.shape[0],wt2.shape[1]:wt1.shape[1]]=wt1[wt2.shape[0]:wt1.shape[0],wt2.shape[1]:wt1.shape[1]]
              # bs[bs2.shape[0]:bs1.shape[0]]=bs1[bs2.shape[0]:bs1.shape[0]]

            # elif(i==nmlayers-1):
            #   wt[wt2.shape[0]:wt1.shape[0],:]=wt1[wt2.shape[0]:wt1.shape[0],:]
            #   # bs[bs2.shape[0]:bs1.shape[0]]=bs1[bs2.shape[0]:bs1.shape[0]]
            else:
              wt[wt2.shape[0]:wt1.shape[0],wt2.shape[1]:wt1.shape[1],wt2.shape[2]:wt1.shape[2],wt2.shape[3]:wt1.shape[3]]=wt1[wt2.shape[0]:wt1.shape[0],wt2.shape[1]:wt1.shape[1],wt2.shape[2]:wt1.shape[2],wt2.shape[3]:wt1.shape[3]]
              # bs[bs2.shape[0]:bs1.shape[0]]=bs1[bs2.shape[0]:bs1.shape[0]]
            global_model.layers[i].set_weights([wt,bs])
          if(len(cluster_model.layers[i].get_weights())==4):
            a,b,c,d=cluster_model.layers[i].get_weights()
            a1,b1,c1,d1=global_model.layers[i].get_weights()
            a2,b2,c2,d2=prev_model.layers[i].get_weights()
            a1[a2.shape[0]:a.shape[0]]=a[a2.shape[0]:a.shape[0]]
            b1[b2.shape[0]:b.shape[0]]=b[b2.shape[0]:b.shape[0]]
            c1[c2.shape[0]:c.shape[0]]=c[c2.shape[0]:c.shape[0]]
            d1[d2.shape[0]:d.shape[0]]=d[d2.shape[0]:d.shape[0]]
            global_model.layers[i].set_weights([a1,b1,c1,d1])
      prev_model=MODEL.build(downsize)
      prev_model.set_weights(cluster_model.get_weights())

      cluster_loss, cluster_acc = test_model(x_test,y_test, cluster_model, comm_round)
      f.write("\nCommunication Round: %d Cluster Model ACCURACY: %f LOSS: %f \n" %(comm_round ,cluster_acc ,cluster_loss))


  # global_model.set_weights(c_model.get_weights())
  global_loss, global_acc = test_model(x_test,y_test, global_model, comm_round)
  f.write("\nCommunication Round: %d GLOBAL MODEL ACCURACY: %f LOSS: %f \n" %(comm_round ,global_acc ,global_loss))
  f.close()








      # print(cluster_model.layers[4].get_weights())


  















#     print("CLIENT NO: ",ind)
    
#     if(ind>5):
#       for lcm_round in range(1):

#       local = MODEL()
#       local_model=local.build(32)
#     elif(ind>=2 and ind<=5):
#       local_model=local.build(16)
#     else:
#       local_model=local.build(8)

    
#     local_model.compile(optimizer=keras.optimizers.Adam(),
#     loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
#     metrics=[keras.metrics.SparseCategoricalAccuracy()],
# )
    
#     local_model.set_weights(global_weights[:4][:4])
#     #trainy[ind]=np.array(trainy[ind]).reshape(-1,1)
#     history=local_model.fit(X[ind],Y[ind], epochs=1)#,validation_data=(x_test,y_test))
#     # print("Accuracy: ",history.history["accuracy"][4])
#     # local_model.evaluate(x_test, y_test)
#     scaling_factor=1.0/5 #1/no.ofclients
#     scaled_weights = scale_model_weights(local_model.get_weights(), scaling_factor)
#     scaled_local_weight_list.append(scaled_weights)
#     K.clear_session()
#   average_weights = sum_scaled_weights(scaled_local_weight_list)
#   #global_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
#   global_model.set_weights(average_weights)
#   #val_acc,val_loss=global_model.evaluate(x_train,y_train)
#   #print(val_loss,val_acc)
#   global_acc, global_loss = test_model(x_test,y_test, global_model, comm_round)

Streaming output truncated to the last 5000 lines.
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 1.0017 - sparse_categorical_accuracy: 0.7459
Client No: 15
Epoch 1/10
79/79 [==============================] - 3s 23ms/step - loss: 0.4703 - sparse_categorical_accuracy: 0.8416
Epoch 2/10
79/79 [==============================] - 2s 23ms/step - loss: 0.3556 - sparse_categorical_accuracy: 0.8844
Epoch 3/10
79/79 [==============================] - 2s 22ms/step - loss: 0.2528 - sparse_categorical_accuracy: 0.9104
Epoch 4/10
79/79 [==============================] - 2s 23ms/step - loss: 0.2386 - sparse_categorical_accuracy: 0.9260
Epoch 5/10
79/79 [==============================] - 2s 22ms/step - loss: 0.2046 - sparse_categorical_accuracy: 0.9320
Epoch 6/10
79/79 [==============================] - 2s 22ms/step - loss: 0.1829 - sparse_categorical_accuracy: 0.9444
Epoch 7/10
79/79 [==============================] - 2s 23ms/step - loss: 0.1815 - sparse_categorical_accura

In [ ]:
len(cluster_model.layers[11].get_weights())

In [ ]:
print(global_loss)

In [ ]:
# print(global_model.get_weights().shape)
a=global_model.get_weights()
print(len(a))
print(len(a[0][0]))
# a=np.array(a,dtype=object)
print(a.shape[0])

In [ ]:
print(a)

In [ ]:
print(a[3])

In [ ]:
for layer in global_model.layers:
    weights = np.array(layer.get_weights())
    print(weights.shape)

In [ ]:
for layer in global_model.layers: print(layer.get_config(), layer.get_weights())

In [ ]:
first_layer_weights = global_model.layers[0].get_weights()[0]
first_layer_biases  = global_model.layers[0].get_weights()[1]
# second_layer_weights = global_model.layers[1].get_weights()[0]
# second_layer_biases  = global_model.layers[1].get_weights()[1]

In [ ]:
print(first_layer_weights.shape,first_layer_biases.shape)

In [ ]:
print(len(global_model.layers))

In [ ]:
for layer in global_model.layers:
    print(layer.input_shape,layer.output_shape)
    if(np.array(layer.get_weights()).shape[0]>=1):
      wt,bs=layer.get_weights()
      print(wt.shape,bs.shape)
      print(len(wt),len(wt[0]))


In [ ]:
for layer in local_model.layers:
    print(layer.input_shape,layer.output_shape)
    if(np.array(layer.get_weights()).shape[0]>=1):
      wt,bs=layer.get_weights()
      print(wt.shape,bs.shape)
      print(len(wt),len(wt[0]))


In [ ]:
print(local_model.get_weights())

In [ ]:
abcd=local_model.get_weights()

In [ ]:
for layer in local_model.layers:
    print(layer.input_shape,layer.output_shape)
    if((np.array(layer.get_weights()).shape[0])>=1):
      wt,bs=layer.get_weights()
      print(wt.shape,bs.shape)
      print(len(wt),len(wt[0]))

In [ ]:
gbwt=np.array(global_model.get_weights())

In [ ]:
print(gbwt[5].shape)

In [ ]:
print(local_model.get_weights)

In [ ]:
print(local_model.get_weights())

In [ ]:
print(len(global_model.layers))

In [ ]:
nmlayers=len(global_model.layers)
for i in range(1,nmlayers-1):
  if(len(global_model.layers[i].get_weights())>0):
    wt,bs=local_model.layers[i].get_weights()
    wt1,bs1=global_model.layers[i].get_weights()
    print(i)
    # print(wt.shape[2],bs.shape[0])
    # print(wt1.shape,bs1.shape)
    print(wt.shape)
    wt=wt1[:,:,:wt.shape[2],:wt.shape[3]]
    bs=bs1[:bs.shape[0]]
    local_model.layers[i].set_weights([wt,bs])
